// Class automatically generated by Dev-C++ New Class wizard
#ifndef SECURITY_H
#define SECURITY_H
#include <iostream>
#include <string>

class Security
{
	public:
		static int validate(string username, string password);
		// class destructor
		//~Security();
};

#endif // SECURITY_H
